# Generated by Django 6.1.1 on 2026-09-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=100)),
                ('issue_type', models.CharField(choices=[('Bus Delay', 'Bus Delay'), ('Overcrowding', 'Overcrowding'), ('Damaged Seat', 'Damaged Seat'), ('Route Problem', 'Route Problem'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('reported_by', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Reported', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
